const convoquestion = [

    'Q1) If you become the principal of the school for one day, what changes would you like to bring and why?',
    'Q2) Why is the divorce rate increasing in India?',
    'Q3) Which news channel do you watch, and why?',
    'Q4) Can two people (Male & female) live together before marriage? If yes, why? If no, why?',
    'Q5) If somebody leaves you in the jungle, how would you come back?',
    'Q6) If given an opportunity to perform on any reality show, would you do it, and why?',
    'Q7) Which mall is the best in Mumbai according to you? Why?',
    'Q8) Do you feel we get things at a cheaper rate in the mall? If yes or no, why?',
    'Q9) Would you like to go for a long drive? Where and why?',
    'Q10) If you get one million dollars, what would you do?',
    'Q11) What is your goal or ambition in your life?',
    'Q12) Would you like to travel abroad? Why?',
    'Q13) What is your view of schools in the future?',
    'Q14) What do you do when you feel bored?',
    'Q15) Which is your favorite attire? Why?',
    'Q16) Who are the people whom you admire the most?',
    'Q17) Which is your favorite color, and why?',
    'Q18) What do you think about the new sea link bridge in Bandra?',
    'Q19) What is your favorite pastime?',
    'Q20) If you could learn any language fluently, what would it be?',
    'Q21) What do you think fashion is?',
    'Q22) Which is your favorite social networking site, and why?',
    'Q23) Describe a classmate whom you admire the most?',
    'Q24) Which is the most pleasant time in 24 hours according to you?',
    'Q25) Do you like to read? Which type of books do you like to read?',
    'Q26) What is the best moment in your life up till now?',
    'Q27) What do you mean by hospitality management?',
    'Q28) Have you organized a party? Where and why?',
    'Q29) Why do women cook at home and not men? According to you, who is the best cook, men or women?',
    'Q30) What is the importance of reading?',
    'Q31) Do you like photography, and why?',
    'Q32) What do you mean by a charitable organization? Which trust would you like to support?',
    'Q33) Do you like to keep pets at home? Which ones?',
    'Q34) What change would you like to bring in Mumbai City?',
    'Q35) What is meant by Business?',
    'Q36) What are the qualities of a manager?',
    'Q37) What type of food do you prefer, vegetarian or non-vegetarian?',
    'Q38) Which is your favorite cuisine, and why?',
    'Q39) What do you do for relaxation?',
    'Q40) Would you like Love marriage or Arrange marriage?',
    'Q41) Would you like to go abroad for study or work? Why?',
    'Q42) Do you like to watch Harry Potter movies? Why?',
    'Q43) Which is the latest movie of Harry Potter? Name it?',
    'Q44) Have you acted in any movie/play/drama? Do you like stage acting or movie acting?',
    'Q45) What type of gifts do you normally give to your friends?',
    'Q46) What is the most precious gift you have got till now?',
    'Q47) Describe our National Flag?',
    'Q48) What is more important to you, your job or salary?',
    'Q49) What concept do you have about International call centres?',
    'Q50) Do you believe marriages are planned in heaven? Why?',
    'Q51) Have you come across any Godly miracle in your life? Describe?',
    'Q52) Would you like to work in a night shift? If yes, why? If no, why?',
    'Q53) Do you agree with the Dowry system or not? Why?',
    'Q54) Do you like people who normally keep on praising themselves? If yes, why? If no, why?',
    'Q55) Do you like the fast life of Mumbai? If yes, why? If no, why?',
    'Q56) Do you feel flowers play an important role in your life? How?',
    'Q57) Do you like Mumbai city? Why?',
    'Q58) What talents do you have?',
    'Q59) How do you manage stress?',
    'Q60) What do you understand by women empowerment?',
    'Q61) What do you think about education? Do you feel children are being overburdened?',
    'Q62) Describe a teacher who has influenced or motivated you?',
    'Q63) Which is your favorite vehicle? Why?',
    'Q64) When is the last time you wrote a letter to someone?',
    'Q65) What are the effects of Global Warming?',
    'Q66) What do you think about the increasing power of the Internet?',
    'Q67) Which is the most important site that gives you maximum information?',
    'Q68) What is the most important thing to learn in English speaking?',
    'Q69) Where would you like to propose to a girl/boy? (Online or Offline)',
    'Q70) Do you agree that girls should have long hair or short hair? Why?',
    'Q71) What are different ways of saving money?',
    'Q72) Who, according to you, is the best personality up till now in Bollywood? Why?',
    'Q73) Which is your most favorite festival? Why?',
    'Q74) Do you feel a married girl should have a share in her father’s property? Why?',
    'Q75) Do we really need new appliances every time in our house?',
    'Q76) What do you mean by keeping the city clean and green?',
    'Q77) Do you agree with the concept of Mumbai as Shanghai? Why?',
    'Q78) What do you mean by true love, and do you feel it still exists? Yes or no?',
    'Q79) Do you agree listening skills can empower your speaking skills?',
    'Q80) What is your name? Do you like your name? What is the meaning of your name?',
    'Q81) What are your strengths and weaknesses?',
    'Q82) Tell me something about your job/business or school/college?',
    'Q83) Do you like to meet people, and why?',
    'Q84) What do you think about Indian Culture?',
    'Q85) Do you like the rituals of marriage or court marriage?',
    'Q86) Which is the most important day in your life since a year?',
    'Q87) In Mumbai, which jobs are better paid?',
    'Q88) What post would you like to hold at the start of your career?',
    'Q89) What is the importance of a job in your life?',
    'Q90) Do you like to read books? What kind of books do you read?',
    'Q91) What do you know about Mass Media?',
    'Q92) Have you seen any 4D theatre? If yes, describe it?',
    'Q93) Have you ever seen any movies on Dinosaurs? What do you think about the creature?',
    'Q94) What is one quality of yourself that you are proud of?',
    'Q95) What is your view about the pandemic?',
    'Q96) Who was your first crush ever?',
    'Q97) List three things that can make you happy anytime?',
    'Q98) List three important qualities you want in your life partner?',
    'Q99) What lesson did you learn from Covid-19?',
    'Q100) What is your view about the Spoken English Course in Bhavans?'
];

export default convoquestion;