const pastquestion = [
    'Q1) Tell me about your last vacation. Where did you go? What did you do?',
    'Q2) What did you do for your last birthday?',
    'Q3) Who was your first crush?',
    'Q4) What was the last really difficult thing you had to do?',
    'Q5) Who did you meet last week?',
    'Q6) Tell me about what you did for the last 24 hours.',
    'Q7) When was the last time you were really excited about something?',
    'Q8) Tell me about where you lived as a child.',
    'Q9) When was the last time you went to an amusement park? How was it?',
    'Q10) What was the best meal you ate recently?',
    'Q11) How did you come here?',
    'Q12) When was the last time you went to a movie theater? What did you see?',
    'Q13) Talk about the last time you were really scared.',
    'Q14) Tell me about your best or worst school teacher.',
    'Q15) What tech problems annoyed you recently?',
    'Q16) What was your first TV like?',
    'Q17) What are some events in the past that made you who you are?',
    'Q18) What bands were popular when you were young?',
    'Q19) When was the last time you were shocked?',
    'Q20) What chores did you have to do when you were young?',
    'Q21) Where did you hang out with your friends last? What did you do?',
    'Q22) Who were some of your favorite sports stars in the past?',
    'Q23) What did they play?',
    'Q24) Why were they your favorite?',
    'Q25) Name some of your country’s famous sports stars of the past.',
    'Q26) Why were they famous?',
    'Q27) What was your best memory from when you were a child?',
    'Q28) What is your earliest memory?',
    'Q29) Which was better for you: elementary school, junior high school, or high school? Why?',
    'Q30) Did you study hard in high school?',
    'Q31) What kinds of food did you eat when you were a child? Do you eat the same things now?',
    'Q32) What was your country like when you were a child?',
    'Q33) Do you think the past was better than the present? Why or why not?',
    'Q34) What were some of the benefits of living in the past?',
    'Q35) Talk about your country’s past (100 years ago). How was the past different from the present: Food, Weddings, Clothing, School, Work, Recreation (free time activities), Communication',
    'Q36) What is your free time activity you like to do and why?',
    'Q37) What type of clothes did you wear in your childhood, and which were your favorites?'
];

export default pastquestion;