const questions = [
  'Q1) what is your name?',
  'Q2) where do you live?',
  'Q3) How members are there in your family?',
  'Q4) How many siblings do you have?',
  'Q5) How many brothers and sisters do you have?',
  'Q6) How much have you studied?',
  'Q7) Do you know the basics in computers?',
  'Q8) Who is your best friend?',
  'Q9) From where did you complete your schooling?',
  'Q10) Which school do you go?',
  'Q11) What is the name of your college?',
  'Q12) Which stream have you selected for your higher studies?',
  'Q13) Which is your favourite subject?',
  'Q14) Who is your favourite teacher?',
  'Q15) What is your hobby?',
  'Q16) What do you like to do in your free time/ leisure time?',
  'Q17) How many malls have you seen in Mumbai ?',
  'Q18) Which is your native place ?',
  'Q19) Who is your favourite actor and actress ?',
  'Q20) Which places do you like to visit in Mumbai ?',
  'Q21) Your favourite Snack ?',
  'Q22) Your favourite fruit ?',
  'Q23) Your favourite colour?',
  'Q24) Your favourite food?',
  'Q25) Your favourite social networking site?',
  'Q26) Which is your favourite outfit?',
  'Q27) Which clothes make you feel comfortable?(Indian / Western)',
  'Q28) Your favourite picnic spots?',
  'Q29) How do you go to School / College / Office ?',
  'Q30) Which is your favourite mode of travel ?',
  'Q31) How much time does it take to reach your school / office / college ?',
  'Q32) How do you commute to your school / college / office ?',
  'Q33)Who is your favourite singer ?',
  'Q34) Which type of Songs do you like ?',
  'Q35) Which is your favourite reality show ?',
  'Q36) Why do you like your mother?',
  'Q37) Why do you like your father?',
  'Q38) How are your neighbours? /Do you have good repo with them?',
  'Q39) How are you? How was your day?',
  'Q40) Do you wish to go abroad for studies or job?',
  'Q41) What is your aim / ambition in your life?',
  'Q42) Do you have a stage fear?',
  'Q43) What do you do when you meet a stranger?',
  'Q44) Do you like sweets? Which is your favourite sweet?',
  'Q45) Are you Vegetarian or non - vegetarian?',
  'Q46) What time do you get up in the morning?',
  'Q47) What do you have for breakfast?',
  'Q48) What time do you have your lunch?',
  'Q49) What do you have for lunch?',
  'Q50) What time do you have your dinner?',
  'Q51) What do you prefer for dinner?',
  'Q52) What time do you sleep?',
  'Q53) How many hours do you sleep?',
  'Q54) Do you take exercise?',
  'Q55) Which is your favourite movie till now?',
  'Q56) What do you do when you feel sad?',
  'Q57) What do you do when you get angry?',
  'Q58) Who is your role model?',
  'Q59) How are you feeling now?',
  'Q60) Where do you like to go with your friends often?',
  'Q61) What good qualities do you have?',
  'Q62) what bad qualities do you have?',
  'Q63) Are you always punctual(on time)?',
  'Q64) Do you have a good understanding with your siblings?',
  'Q65) If unmarried, which type of marriage would you prefer Arranged or love marriage?',
  'Q66) What is beauty according to you?',
  'Q67) Whom do you select to be your friends?',
  'Q68) Do you like to work in team or alone?',
  'Q69) What are your achievements till now?',
  'Q70) Do you believe in destiny or hard work?',
  'Q71) Have you visited any orphanage till now?',
  'Q72) How do you celebrate your birthday?',
  'Q73) Are you good at remembering dates?',
  'Q74) Do you believe in incarnation?',
  'Q75) which is your favourite animal?',
  'Q76) which is you favourite bird?',
  'Q77) How do you react in adverse situation?',
  'Q78) Have you planned your career?',
  'Q79) Do you believe in doing charity?',
  'Q80) Do you believe in dowry system? (Yes / No) why?',
  'Q81) What qualities would you like to have in your life partner?',
  'Q82) What do you think about incredible India?',
  'Q83) Educating a girl child is important or no?',
  'Q84) ',
  'Q85) According to you what is important money or wisdom?',
  'Q86) Which quality of a person attracts you the most?',
  'Q87) Do you know to cook? What do you cook?',
  'Q88) What is marriage according to you?',
  'Q89) Women working in night shifts. Do you like this concept?',
  'Q90) What is addiction?',
  'Q91) Are you addicted to anything? (Yes / No) why.',
  'Q92) Why learning English language is important?',
  'Q93) How many languages do you know?',
  'Q94) Are you passionate about learning new things?',
  'Q95) Which is your favourite Hollywood or Bollywood?',
  'Q96) Are you religious?',
  'Q97) what is humanity according to you?',
  'Q98) Have you given or taken bribe to get the work done?',
  'Q99) If you get a chance to enter into politics would you?',
  'Q100) How are you feeling now after exploring yourself?'

];

export default questions;