const questions = {
    1: 'Q1) what is your name?',
    2: 'Q2) where do you live?',
    3: 'Q3) How members are there in your family?',
    4: 'Q4) How many siblings do you have?',
    5: 'Q5) How many brothers and sisters do you have?',
    6: 'Q6) How much have you studied?',
    7: 'Q7) Do you know the basics in computers?',
    8: 'Q8) Who is your best friend?',
    9: 'Q9) From where did you complete your schooling?',
    10: 'Q10) Which school do you go?',
    11: 'Q11) What is the name of your college?',
    12: 'Q12) Which stream have you selected for your higher studies?',
    13: 'Q13) Which is your favourite subject?',
    14: 'Q14) Who is your favourite teacher?',
    15: 'Q15) What is your hobby?',
    16: 'Q16) What do you like to do in your free time/ leisure time?',
    17: 'Q17) How many malls have you seen in Mumbai ?',
    18: 'Q18) Which is your native place ?',
    19: 'Q19) Who is your favourite actor and actress ?',
    20: 'Q20) Which places do you like to visit in Mumbai ?',
    21: 'Q21) Your favourite Snack ?',
    22: 'Q22) Your favourite fruit ?',
    23: 'Q23) Your favourite colour?',
    24: 'Q24) Your favourite food?',
    25: 'Q25) Your favourite social networking site?',
    26: 'Q26) Which is your favourite outfit?',
    27: 'Q27) Which clothes make you feel comfortable?(Indian / Western)',
    28: 'Q28) Your favourite picnic spots?',
    29: 'Q29) How do you go to School / College / Office ?',
    30: 'Q30) Which is your favourite mode of travel ?',
    31: 'Q31) How much time does it take to reach your school / office / college ?',
    32: 'Q32) How do you commute to your school / college / office ?',
    33: 'Q33)Who is your favourite singer ?',
    34: 'Q34) Which type of Songs do you like ?',
    35: 'Q35) Which is your favourite reality show ?',
    36: 'Q36) Why do you like your mother?',
    37: 'Q37) Why do you like your father?',
    38: 'Q38) How are your neighbours? /Do you have good repo with them?',
    39: 'Q39) How are you? How was your day?',
    40: 'Q40) Do you wish to go abroad for studies or job?',
    41: 'Q41) What is your aim / ambition in your life?',
    42: 'Q42) Do you have a stage fear?',
    43: 'Q43) What do you do when you meet a stranger?',
    44: 'Q44) Do you like sweets? Which is your favourite sweet?',
    45: 'Q45) Are you Vegetarian or non - vegetarian?',
    46: 'Q46) What time do you get up in the morning?',
    47: 'Q47) What do you have for breakfast?',
    48: 'Q48) What time do you have your lunch?',
    49: 'Q49) What do you have for lunch?',
    50: 'Q50) What time do you have your dinner?',
    51: 'Q51) What do you prefer for dinner?',
    52: 'Q52) What time do you sleep?',
    53: 'Q53) How many hours do you sleep?',
    54: 'Q54) Do you take exercise?',
    55: 'Q55) Which is your favourite movie till now?',
    56: 'Q56) What do you do when you feel sad?',
    57: 'Q57) What do you do when you get angry?',
    58: 'Q58) Who is your role model?',
    59: 'Q59) How are you feeling now?',
    60: 'Q60) Where do you like to go with your friends often?',
    61: 'Q61) What good qualities do you have?',
    62: 'Q62) what bad qualities do you have?',
    63: 'Q63) Are you always punctual(on time)?',
    64: 'Q64) Do you have a good understanding with your siblings?',
    65: 'Q65) If unmarried, which type of marriage would you prefer Arranged or love marriage?',
    66: 'Q66) What is beauty according to you?',
    67: 'Q67) Whom do you select to be your friends?',
    68: 'Q68) Do you like to work in team or alone?',
    69: 'Q69) What are your achievements till now?',
    70: 'Q70) Do you believe in destiny or hard work?',
    71: 'Q71) Have you visited any orphanage till now?',
    72: 'Q72) How do you celebrate your birthday?',
    73: 'Q73) Are you good at remembering dates?',
    74: 'Q74) Do you believe in incarnation?',
    75: 'Q75) which is your favourite animal?',
    76: 'Q76) which is you favourite bird?',
    77: 'Q77) How do you react in adverse situation?',
    78: 'Q78) Have you planned your career?',
    79: 'Q79) Do you believe in doing charity?',
    80: 'Q80) Do you believe in dowry system? (Yes / No) why?',
    81: 'Q81) What qualities would you like to have in your life partner?',
    82: 'Q82) What do you think about incredible India?',
    83: 'Q83) Educating a girl child is important or no?',
    84: 'Q84) ',
    85: 'Q85) According to you what is important money or wisdom?',
    86: 'Q86) Which quality of a person attracts you the most?',
    87: 'Q87) Do you know to cook? What do you cook?',
    88: 'Q88) What is marriage according to you?',
    89: 'Q89) Women working in night shifts. Do you like this concept?',
    90: 'Q90) What is addiction?',
    91: 'Q91) Are you addicted to anything? (Yes / No) why.',
    92: 'Q92) Why learning English language is important?',
    93: 'Q93) How many languages do you know?',
    94: 'Q94) Are you passionate about learning new things?',
    95: 'Q95) Which is your favourite Hollywood or Bollywood?',
    96: 'Q96) Are you religious?',
    97: 'Q97) what is humanity according to you?',
    98: 'Q98) Have you given or taken bribe to get the work done?',
    99: 'Q99) If you get a chance to enter into politics would you?',
    100: 'Q100) How are you feeling now after exploring yourself?'

  };

export default questions;